### ISSUE TITLE
Is it possible to load excel files, Image files and document files with this plugin?

### ISSUE THREAD

**Issue by kumarandena** [svzi/nativescript-pdfbox#1]
Sorry for asking question here!

I have the requirement to load excel files, Image files and document files inside the Nativescript angular application.

Is it possible to load mentioned files as like as pdf files?
Of if a small workaround on this plugin will help to load mentioned documents files? If yes please suggest.

**Comment by svzi** [comment]
@kumarandena I'm sorry but I didn't see this issue. As far as I remember I didn't even receive a notification for that. :disappointed: 

I did not investigate the possibility to load your mentioned files and I assume your question is very long outdated. For that reason I close this issue. Sorry again!

**Comment by kumarandena** [comment]
@svzi thats ok. Still I did not get any workarounds to preview/load the excel or other document files inside the application. So i have changed the functionality to download the excel/doc file instead of preview.  

Anyway thanks for your response.

**Comment by svzi** [comment]
@kumarandena At least this time I got a notification. Yay! :smile: 

Are you looking for an Android only solution? In that case I would download the file as well and then start an intent to open the file.

**Comment by kumarandena** [comment]
@svzi 😄Yes.

I am looking for both Android/Ios platforms solution. Good idea. I thought the same for android that time but i did not try that. Do you have any similar workaround like this? It would be helpful to continue. 

And Ios i did not get any idea.

**Comment by svzi** [comment]
@kumarandena You could try this: https://github.com/rafear/nativescript-handle-file

If that doesn't work as expected, I would look for other plugins or try to have a look at a working cordova-plugin like this:
https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/android/io/github/pwlin/cordova/plugins/fileopener2/FileOpener2.java

I've also read that we can use cordova-plugins with NativeScript, but I haven't tried myself. That would be my fallback: https://github.com/pwlin/cordova-plugin-file-opener2

**Comment by kumarandena** [comment]
@svzi Thanks for showing me the right direction. 

In **nativescript-handle-file** plugin- If i am not wrong, Its possible to load the file from url only not from device file system/local storage. 
https://github.com/rafear/nativescript-handle-file/blob/master/demo/app/main-view-model.ts#L44

Note - In my use case, I am having the document file in local file system. So When user tap the filename in UI then need to do intent that will allow to open available other apps which will support the actual file.

Thanks for your fallback suggestion.
Regarding cordova plugins, I will try to write a wrapper/plugin for nativescript support. Before that i need to take deep understanding of how to wrap cordova plugins for nativescript support.
